
server:
  port: 8080
  address: 0.0.0.0


spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: false
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2

logging:
  level:
    web: INFO
    org:
      springframework:
        web:  INFO
